### ISSUE TITLE
Execute the DA jjobs outside of the workflow management

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1194]
**Description**
Develop an application that will execute a sequence of jjobs outside of rocoto. This will be limited to the ```cycled``` applications and probably to the JEDI implementation work at first.

This is useful for development when one would need to run a single cycle. This capability currently exists in some state under ```sorc/gdas.cd```, but @aerorahul suggested it should live somewhere in this repository.

**Solution**
The user input is too long to be passed as a regular list of arguments, so make the input of the application be a ```yaml``` file that will be parsed by the application. It will look something like this:

```run_jjob.py run_jjobs.yaml```
where ```run_jjobs.yaml``` would look like this:
```yaml
gw environement: # Variables that will have to be exported in order to run the jjobs
  experiment identifier:
    PSLOT: gdas_test
    HOMEgfs: /pathto/global-workflow

  cycle info:
    PDY: 20180415
    cyc: 12

  backgrounds:
    COMIN_GES: /pathto/bkgs

  r2d2:
    R2D2_OBS_SRC: 'gdasapp'
    R2D2_OBS_DUMP: 'soca'

  working directories:
    ROTDIRS: /pathto/ROTDIRS
    EXPDIRS: /pathto/EXPDIRS
    STMP: /pathto/STMP

jjobs: # A list of properly ordered jjobs 
 - JGDAS_GLOBAL_OCEAN_ANALYSIS_PREP
 - JGDAS_GLOBAL_OCEAN_ANALYSIS_RUN
 - JGDAS_GLOBAL_OCEAN_ANALYSIS_POST

configs: # The dictionary passed to setup_expt.py to overwite defaults
  ocnanal:
    SOCA_INPUT_FIX_DIR: /pathetosocastaticfiles'
    CASE_ANL: 'C24'
    COMIN_OBS: '/pathtor2d2db/'
    SOCA_NINNER: 3
    R2D2_OBS_SRC: 'gdasapp'
    R2D2_OBS_DUMP: 'soca'
``` 

```run_jjob.py``` takes the above ```yaml``` as input and generates a bash script that can be executed or sbatched and will run the list of ```jjobs``` in sequence.
