### ISSUE TITLE
Stage initial conditions stored on HPSS

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/global-workflow#2988]
### What new functionality do you need?

Most jobs require the initial conditions to be available on local disk.  The `stage_ic` job copies/stages these initial condition into the experiment's `COM` directory.
This issue extends that functionality to copy from HPSS (on HPSS accessible machines) into `COM`.

### What are the requirements for the new functionality?

The requirements for this functionality lies in 2 spaces:
- wxflow
  - `hpss.py` and `htar.py` have the code to pull from HPSS
- global-workflow
  - The inverse of `archive` needs to be coded in `stage_ic` in providing the yaml with location of the tarball and its contents.

### Acceptance Criteria

- [ ] fetch tarball
- [ ] unpack tarball
- [ ] stage contents of the tarball

**Comment by aerorahul** [comment]
An example yaml extending `stage_atm_cold.yaml` 
```yaml
untar:
    tarball : "{{ ATARDIR }}/{{ cycle_YMDH }}/atm_cold.tar"
    on_hpss: True
    contents:
        - gfs_ctrl.nc
        {% for ftype in ["gfs_data", "sfc_data"] %}
        {% for ntile in range(1, ntiles + 1) %}
        - {{ ftype }}.tile{{ ntile }}.nc
        {% endfor %} # ntile
        {% endfor %} # ftype
    destination: "{{ DATA }}"
atmosphere_cold:
    copy:
        - ["{{ DATA }}/gfs_ctrl.nc", "{{ COMOUT_ATMOS_INPUT }}"]
        {% for ftype in ["gfs_data", "sfc_data"] %}
        {% for ntile in range(1, ntiles + 1) %}
        - ["{{ DATA }}/{{ ftype }}.tile{{ ntile }}.nc", "{{ COMOUT_ATMOS_INPUT }}"]
        {% endfor %} # ntile
        {% endfor %} # ftype
```
